---
# handlers file for installer_lenkins


- name: sleep for 30 seconds and continue with play
  wait_for: timeout=50
  delegate_to: localhost

- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout

